[colors.bright]
black = "#000000"
blue = "#4D4DFF"
cyan = "#4BF0FC"
green = "#33ff00"
magenta = "#7a72e5"
red = "#e01b24"
white = "#ffffff"
yellow = "#ffb000"

[colors.cursor]
cursor = "#C02157"
text = "#181446"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#000000"
blue = "#4D4DFF"
cyan = "#4BF0FC"
green = "#33ff00"
magenta = "#7a72e5"
red = "#e01b24"
white = "#ffffff"
yellow = "#ffb000"

[colors.primary]
background = "#181446"
dim_foreground = "#C02157"
foreground = "#C02157"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[font]
normal.family = "Fira Code" 
bold.family = "Fira Code" 
italic.family = "Fira Code" 
bold_italic.family = "Fira Code" 
